packer {
  required_plugins {
    amazon = {
      source  = "github.com/hashicorp/amazon"
      version = "~> 1"
    }
  }
}

// variable "aws_access_key" {
//   type    = string
//   default = "${env("AWS_ACCESS_KEY_ID")}"
// }

// variable "aws_secret_access_key" {
//   type    = string
//   default = "${env("AWS_SECRET_ACCESS_KEY")}"
// }

// variable "aws_region" {
//   type    = string
//   default = "${env("AWS_REGION")}"
// }

# "timestamp" template function replacement
locals { timestamp = regex_replace(timestamp(), "[- TZ:]", "") }

source "amazon-ebs" "autogenerated_1" {
  ami_name      = "packer prerequisites ${local.timestamp}"
  instance_type = "t2.micro"
  source_ami    = "ami-0381840963c35cb1f"

  communicator = "winrm"
  user_data_file = "./bootstrap_win.txt"
  winrm_password = "SuperS3cr3t!!!!"
  winrm_username  = "Administrator"
}

build {
  sources = ["source.amazon-ebs.autogenerated_1"]

  provisioner "powershell" {
    script = "./prerequisites.ps1"
  }

  post-processor "manifest" {
    output = "prerequisites_ami.json"
    strip_path = true
  }
}
