name: SonarCloud analysis

on:
  workflow_call:
  workflow_dispatch:

permissions:
  pull-requests: read # allows SonarCloud to decorate PRs with analysis results

jobs:
  Analysis:
    runs-on: ubuntu-latest

    steps:
      - name: Analyze with SonarCloud
        uses: sonarsource/sonarcloud-github-action@master
        env:
          SONAR_TOKEN: ${{ secrets.SONAR_TOKEN }}
          # Additional arguments for the sonarcloud scanner
          args:
            -Dsonar.projectKey=biancapistea_webApi
            -Dsonar.organization=biancapistea
