name: SonarCloud analysis

on:
  push:
    branches: [ "main" ]
  pull_request:
    branches: [ "main" ]
  workflow_dispatch:

permissions:
  pull-requests: read # allows SonarCloud to decorate PRs with analysis results
  
# on:
#   workflow_call:
#   workflow_dispatch:

jobs:
  Analysis:
    runs-on: ubuntu-latest

    steps:
      - name: Analyze with SonarCloud
        uses: sonarsource/sonarcloud-github-action@master
        with:
          token: ${{ secrets.SONAR_TOKEN }}
          args: |
            -Dsonar.projectKey=biancapistea_webApi
            -Dsonar.organization=biancapistea
